services:
  app:
    build: .
    container_name: ps9-cv-checker
    volumes:
      - .:/app
    working_dir: /app
    tty: true              # <- ermÃ¶glicht interaktive Shell
    stdin_open: true       # <- erlaubt Eingaben
    command: bash  