# you will find a sticker inside the battery cavity with wifi, admin, and username “user” credentials
robot:
  wifi: 'wlan0'
  user: 'robot'
  password: 'Super Secret Password'
  ip: '192.168.80.3'