sqlite:
    database: '/workspaces/PS9-Boston-Dynamic-Mobile-CV-Testing-Systems/db/ps9.db'
    timeout: 7
    detect_types: 0
    isolation_level: 'DEFERRED'
    check_same_thread: True
    cached_statements: 128
    uri: False