sqlite:
    database: !!str '/workspaces/PS9-Boston-Dynamic-Mobile-CV-Testing-Systems/db_data/ps9.db'
    timeout: !!int 7
    detect_types: !!int 0
    isolation_level: !!str 'DEFERRED'
    check_same_thread: !!bool True
    cached_statements: !!int 128
    uri: !!bool False